### ISSUE TITLE
Please migrate to latest flutter version 3.22.1

### ISSUE THREAD

**Issue by ps6067966** [zezo357/path_finding#3]

**Comment by abdelaziz-mahdy** [comment]
Does the app fail to compile? I don't think I had anything that needed migration in this app.

But will check thank you

**Comment by ps6067966** [comment]
> Does the app fail to compile? I don't think I had anything that needed migration in this app.
> 
> But will check thank you

in new version flutter web index.html file is changed. 
and I'm not able to figure out, how to use loading indicator with new stable version.

**Comment by abdelaziz-mahdy** [comment]
Oh yes, I had a problem with that too, looks like we will need to edit the templates, this will take sometime since I can't figure out how to track the progress yet

**Comment by abdelaziz-mahdy** [comment]
migrated in the last commit, so check it please
